version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:5000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm start
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=crud_db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start
    stdin_open: true
    tty: true

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: crud_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db-data:
